### ISSUE TITLE
Link entries items to form on  "edit entry" page

### ISSUE THREAD

**Issue by adamish717** [Sinetheta/steam-hours#23]
The issue:  When clicking "Edit Entry", the details from that entry were not being brought over to the form for editing.

I've MOSTLY fixed it.  The only thing I haven't been able to draw in is the timepicker information.  All other fields have been verified working locally.

File:  app/assets/views/entries/_form.html.erb
Gist: https://gist.github.com/adamish717/0ccddcc56e390ac9354b

**Comment by Sinetheta** [comment]
I'm too lazy to check this, re-open is my recent entry form rework didn't fix this.
