### ISSUE TITLE
Show PO's on individual Client page

### ISSUE THREAD

**Issue by adamish717** [Sinetheta/steam-hours#25]
Top Container: Client Name + Back/Edit/Delete buttons
Middle Container: Show all active PO's with links
Bottom Container: Show all inactive PO's with links

File: app/views/clients/show.html.erb
Gist: https://gist.github.com/adamish717/36c2b8027d249176f3bf

Needs to be done:  Grab active/inactive PO's and have them auto-populate in the table.

**Comment by Sinetheta** [comment]
User clients or admin clients?

**Comment by adamish717** [comment]
All clients are admin clients.  "Users" don't see ANY page except their own entries.

**Comment by Sinetheta** [comment]
Then we should be referring to it as the admin clients view. It's fine to handle that as a single issue, but let's make sure we move things which need to be moved it will make it easier to restrict access. We're not going to have "admin only" endpoints which are not under the /admin namespace.
