### ISSUE TITLE
List all Entries on Individual PO Page

### ISSUE THREAD

**Issue by adamish717** [Sinetheta/steam-hours#27]
When clicking a specific PO, all Entries for that PO should be listed on that page

File: app/views/purchase_orders/show.html.erb
Gist: https://gist.github.com/adamish717/0bc6b446e99d83f2ee7f

**Comment by Sinetheta** [comment]
User POs or admin POs?

**Comment by adamish717** [comment]
All PO's are admin PO's.  User's only see their own entries, and their entry page
