### ISSUE TITLE
Fix seed data

### ISSUE THREAD

**Issue by adamish717** [Sinetheta/steam-hours#31]
Seed data is a little unclear when verifying pages are working as intended.

New Seed Data:

Clients:
- Red
- Green
- Blue

PO's for Red:
- Red-Orange
- Red-Yellow
- Red-Silver

PO's for Green:
- Green-Orange
- Green-Yellow
- Green-Silver

PO's for Blue:
- Blue-Orange
- Blue-Yellow
- Blue-Silver

Existing seed data for entries is good.

**Comment by Sinetheta** [comment]
Okay, okay, okay. It may have been a waste of time. But I upped the hilarity factor of our seed data by a factor of roughly 1 billion.
