### ISSUE TITLE
Make "entries page" mobile friendly

### ISSUE THREAD

**Issue by adamish717** [Sinetheta/steam-hours#33]
The tables don't compress nicely with their current layout.  Information in comments on GIST as well.

Line 20: Change
"5 hours and 5 minutes"
TO
"5 hrs 5 min"

In Gist, I have:
- Line 8: Changed the wording of the ambiguous "description" to a more accurate "work performed"
- Line 16: Changed the date format to just "Month Day". The year is obvious, and if it's not, it's stated in the "from-to" in the pay-period heading
- Line 30: Removed line 30 "Show hours billed" as that's not staff information

File: app/views/entries/_entry.html.erb
GIST: https://gist.github.com/adamish717/dae0b731e2b9dfefd72a

**Comment by Sinetheta** [comment]
> Line 30: Removed line 30 "Show hours billed" as that's not staff information

Does it become _staff information_ if we call it "time logged"? It's not exactly secret knowledge, it's the total of the hours they just typed in. I only included to highlight time they may have accidentally "double booked". But if it doesn't add value, then we'll drop it.

**Comment by Sinetheta** [comment]
> Line 20: After searching, I couldn't find where the wording for the Per-Entry time is located. Desired change is:

Checking out the [blame for that line](https://github.com/Sinetheta/steam-hours/blame/master/app/views/entries/_entry.html.erb#L20) shows that it came in with a commit [Use Radar's dotiw to format time durations](https://github.com/Sinetheta/steam-hours/commit/17aa234e51ddf6900f9c7542baa5fbb24816c20b).
